spring:
  profiles:
    active: sqlite

---
spring:
  config:
    activate:
      on-profile: sqlite

  application:
    name: MovieDB

  datasource:
    hikari:
      jdbc-url: jdbc:sqlite:mysqlitedb.db
      username: admin
      password: admin
      driver-class-name: org.sqlite.JDBC

  # jpa specific settings
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
